security:
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v3/api-docs
      - /*/error
      - /csrf
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: tit-auth
          uri: lb://tit-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 代码生成
        - id: tit-gen
          uri: lb://tit-gen
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: tit-system
          uri: lb://tit-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
