tit:
  name: tit
  desc: tit
  config:
    # 密码最大错误次数
    passwordMaxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    passwordLockTime: 10
    tokenTimeout: 60
    tempFolder: temp
    fileStorage: file
  docs:
    title: ${tit.name}
    description: ${tit.desc}
    contact: ${user.name}
    version: 1.0.0